[package]
name = "fm-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[[bin]]
name = "fm-server"
path = "src/bin/main.rs"
test = false
doctest = false

[dependencies]
aide.workspace = true
arcstr.workspace = true
async-trait.workspace = true
axum-extra.workspace = true
axum-jsonschema.workspace = true
axum-macros.workspace = true
axum-tracing-opentelemetry.workspace = true
axum.workspace = true
clap.workspace = true
eyre.workspace = true
init-tracing-opentelemetry.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
tokio = { workspace = true, features = ["net"] }
uuid.workspace = true

# local deps
sblex.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
eyre.workspace = true
reqwest.workspace = true
