[package]
name = "fm-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[[bin]]
name = "fm-server"
path = "src/bin/main.rs"
test = false
doctest = false

[dependencies]
aide.workspace = true
arcstr.workspace = true
async-trait.workspace = true
axum-extra.workspace = true
axum-jsonschema.workspace = true
axum-macros.workspace = true
axum-tracing-opentelemetry.workspace = true
axum.workspace = true
clap.workspace = true
eyre.workspace = true
init-tracing-opentelemetry = { workspace = true, features = ["stdout"] }
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

# local deps
sblex.workspace = true
workspace-hack.workspace = true

# opentelemetry-stdout = { version = "0.3.0", features = [
#     "trace",
#     "logs",
#     "metrics",
# ] }
# opentelemetry-semantic-conventions = "0.14.0"
# opentelemetry-otlp = { version = "0.15.0", features = ["logs", "reqwest-client", "reqwest-rustls"] }
tower-http = { version = "0.5.2", features = ["trace", "timeout"] }
tracing-opentelemetry-instrumentation-sdk = "0.17.1"
opentelemetry-otlp = { version = "0.14", features = [
    "reqwest-client",
    "reqwest-rustls",
] }
dotenvy = "0.15.7"
config = "0.14.0"
serde_derive = "1.0.197"

[dev-dependencies]
eyre.workspace = true
reqwest.workspace = true
insta.workspace = true
